FROM golang:1.27.0-alpine AS builder

WORKDIR /app

# Copier les fichiers de dépendances
# Копирование файлов зависимостей
COPY go.mod go.sum ./
COPY comon-backend ./comon-backend
RUN go mod download

# Copier tout le code
# Копирование всего кода
COPY . .

# Compiler
# Компиляция
RUN CGO_ENABLED=0 GOOS=linux go build -o user-service cmd/user-service/main.go

# Image finale
# Финальный образ
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/user-service .
EXPOSE 8081
CMD ["./user-service"]